### PR TITLE
Add fix for directive-is-now-an-element rules

### PR DESCRIPTION
**Pull request by j3gb3rt**
Resolves https://github.com/ionic-team/v4-migration-tslint/issues/14

### CODE REVIEW

**Comment by j3gb3rt** [comment]
@cwoolum or @dwieeb, any idea what the failure from circleci means?

```
Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}
```

All the tests passed. Seem to fail running a coveralls task?

**Comment by dwieeb** [comment]
@j3gb3rt I'm guessing it's because we don't give our secret to PRs for contributors, and Coveralls requires a token. I'm not sure how Coveralls expects us to do this. Any thoughts, @cwoolum?

**Comment by j3gb3rt** [comment]
@cwoolum Bump

**Comment by dwieeb** [comment]
@j3gb3rt I've been testing this locally and everything is looking great.

One concern I had is that the unit tests could use more test cases for additional elements within and surrounding the affected elements. For example, `<ion-list radio-group>` [can contain many `ion-item` elements](https://ionicframework.com/docs/api/components/radio/RadioGroup/), etc. Additionally, any of these elements can be surrounded by an `ion-content` element, for example.

I am going to approve this, because it wouldn't be hard to add the test cases. I've already verified that they are working.

**Comment by dwieeb** [comment]
@j3gb3rt Can I put your username in the README for contributing to these rules?

**Comment by j3gb3rt** [comment]
Sorry for the delay. Yes you can add my username. I can add more test cases, but it may be a few days.

**Comment by dwieeb** [comment]
@j3gb3rt No worries. Thank you for submitting the PR!

**Comment by cwoolum** [comment]
Sorry, just caught up to this. Looks like the issue was resolved.

**Pull request merged**
